#!/data/data/com.termux/files/usr/bin/bash

if [ ! -w "$PREFIX/bin/python" ]
then
        pkg install python
        pkg install python3
fi

if [ ! -w "$PREFIX/lib/python3.11/site-packages/colorama" ]
then
        pip install colorama
fi


if [ ! -w "$PREFIX/bin/figlet" ]
then
        pkg install figlet
fi


if [ ! -w "$PREFIX/lib/python3.11/site-packages/lolpython" ]
then
        pip install lolpython
fi


if [ -w "$PREFIX/opt/HackTools/hacktools.py" ]
then
        rm -rf $PREFIX/opt/HackTools
        git clone https://github.com/codepreceptor/HackTools $PREFIX/opt/HackTools
        cd $PREFIX/opt/HackTools
        python3 hacktools.py
        termux-open-url https://t.me/codepreceptor

else
        pkg install git
        git clone https://github.com/codepreceptor/HackTools $PREFIX/opt/HackTools
        cd $PREFIX/opt/HackTools
        python3 hacktools.py
        termux-open-url https://t.me/codepreceptor
fi
